id = "objective-c"
name = "Objective-C"
version = "0.2.0"
schema_version = 1
authors = ["bapuwang7@gmail.com", "dgkngk99@gmail.com"]
description = "Objective-C language support for Zed"
repository = "https://github.com/dgkngk/zed-objective-c-extension"

[grammars.objc]
repository = "https://github.com/merico-dev/tree-sitter-objc"
rev = "2e87d715a35a6d87e6f7c5dd2e02fa73d8461df9"

[language_servers.clangd]
name = "clangd"
languages = ["Objective-C"]

[package.metadata.zed]
language = "objc"
